update font and fix more [in progress]
ScuffleCloud/landing pull request #6
Opened 2024-12-17 03:36 UTC by lucassshanks

## Motivation

## Solution

## Tickets

2025-01-06 12:49 UTC, lennartkloock requested changes
A few things I've noticed:
- The <title> for each page is missing
- The favicon is missing
- Indentation is 2 spaces instead of 4 (doesn't really matter but I prefer 4)
- All files in the `lib/images` folder can be renamed to `.svelte` instead of `.svg` to make them Svelte components. This way it would no longer be required to use the `<img>` element to render them, instead the normal Svelte component syntax could be used.

2025-01-06 12:49 UTC, lennartkloock commented on package.json
>    }
All dependencies should be `devDependencies`

2025-01-06 12:49 UTC, lennartkloock commented on src/components/roadmap/Hero.svelte
> +    <a href="https://jira.scuffle.cloud/" class="pill-link">
I would extract this link into an env var to make it easily changeable later.

2025-01-06 12:49 UTC, lennartkloock commented on src/lib/consts.ts
> +export const BLOG_URL = 'https://bytes.scuffle.cloud/';
I feel like those should be env vars to take advantage of vite build modes

2025-01-07 11:50 UTC, lucassshanks commented
> A few things I've noticed:
> 
> * The <title> for each page is missing
> * The favicon is missing
> * Indentation is 2 spaces instead of 4 (doesn't really matter but I prefer 4)
> * All files in the `lib/images` folder can be renamed to `.svelte` instead of `.svg` to make them Svelte components. This way it would no longer be required to use the `<img>` element to render them, instead the normal Svelte component syntax could be used.

Nice makes sense. Updated a bunch of stuff

2025-01-07 22:40 UTC, lennartkloock approved these changes
lgtm now :)

2025-01-08 01:12 UTC, merged